export interface Place {
  id: string;
  name: string;
  city: string;
  state: string;
  country: string;
  type: "restaurant" | "cafe" | "adventure" | "entertainment";
  cuisine?: string;
  image: string;
  rating: number;
  reviewCount: number;
  distance: number;
  priceLevel: 1 | 2 | 3;
  isOpen: boolean;
  address: string;
  description: string;
  bestTimeToVisit: string;
  recommendedFor: string[];
  tags: string[];
  mood: string[];
  companion: string[];
  photos: string[];
  reviews: Review[];
  lat: number;
  lng: number;
  trending?: boolean;
  sponsored?: boolean;
}

export interface Review {
  id: string;
  user: string;
  rating: number;
  text: string;
  date: string;
}

export interface Reel {
  id: string;
  placeId: string;
  placeName: string;
  image: string;
  caption: string;
  creator: string;
  likes: number;
  views: number;
}

const RESTAURANT_IMAGES = [
  "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1559329007-40df8a9345d8?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=600&h=400&fit=crop",
];

const CAFE_IMAGES = [
  "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1445116572660-236099ec97a0?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1559305616-3f99cd43e353?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=600&h=400&fit=crop",
];

const ADVENTURE_IMAGES = [
  "https://images.unsplash.com/photo-1551632811-561732d1e306?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1519904981063-b0cf448d479e?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1501555088652-021faa106b9b?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1533587851505-d119e13fa0d7?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1528543606781-2f6e6857f318?w=600&h=400&fit=crop",
];

const ENTERTAINMENT_IMAGES = [
  "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1511882150382-421056c89033?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1513106580091-1d82408b8cd6?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1560169897-fc0cdbdfa4d5?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1570498839593-e565b39455fc?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1543946207-39bd91e70ca7?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1585951237318-9ea5e175b891?w=600&h=400&fit=crop",
];

export const PLACES: Place[] = [
  {
    id: "restaurants_1",
    name: "Paradise Biryani",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "restaurant",
    cuisine: "Hyderabadi",
    image: RESTAURANT_IMAGES[0],
    rating: 4.1,
    reviewCount: 4820,
    distance: 1.2,
    priceLevel: 2,
    isOpen: true,
    address: "MG Road, Secunderabad, Hyderabad",
    description: "The legendary Paradise Biryani is an iconic Hyderabadi restaurant known worldwide for its signature Hyderabadi Dum Biryani. Serving since 1953, it remains the gold standard for authentic biryani lovers.",
    bestTimeToVisit: "12:00 PM - 2:00 PM",
    recommendedFor: ["Family", "Friends", "Solo"],
    tags: ["Biryani", "Hyderabadi", "Iconic", "Non-Veg"],
    mood: ["chill", "fun", "budget"],
    companion: ["friends", "family", "parents", "solo", "college"],
    photos: [RESTAURANT_IMAGES[0], RESTAURANT_IMAGES[6], RESTAURANT_IMAGES[7]],
    reviews: [
      { id: "r1", user: "Arjun K.", rating: 5, text: "The best biryani in all of Hyderabad. No trip to the city is complete without eating here!", date: "2 days ago" },
      { id: "r2", user: "Sneha P.", rating: 4, text: "Always consistent quality. The mutton biryani is outstanding.", date: "1 week ago" },
    ],
    lat: 17.386,
    lng: 78.4877,
    trending: true,
  },
  {
    id: "restaurants_2",
    name: "Shah Ghouse Restaurant",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "restaurant",
    cuisine: "Mughlai",
    image: RESTAURANT_IMAGES[1],
    rating: 4.2,
    reviewCount: 3210,
    distance: 2.8,
    priceLevel: 3,
    isOpen: true,
    address: "Tolichowki, Hyderabad",
    description: "Shah Ghouse is famous for its late-night biryani and kebabs. A Hyderabad institution that comes alive after sunset, known for its rich Mughlai flavors.",
    bestTimeToVisit: "8:00 PM - 11:00 PM",
    recommendedFor: ["Friends", "College Groups", "Late Night"],
    tags: ["Mughlai", "Kebabs", "Late Night", "Non-Veg"],
    mood: ["fun", "chill", "budget"],
    companion: ["friends", "college"],
    photos: [RESTAURANT_IMAGES[1], RESTAURANT_IMAGES[8], RESTAURANT_IMAGES[5]],
    reviews: [
      { id: "r3", user: "Ravi M.", rating: 5, text: "The haleem during Ramadan is absolutely divine!", date: "3 days ago" },
    ],
    lat: 17.387,
    lng: 78.4887,
    sponsored: true,
  },
  {
    id: "restaurants_3",
    name: "Chutneys",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "restaurant",
    cuisine: "South Indian",
    image: RESTAURANT_IMAGES[2],
    rating: 4.3,
    reviewCount: 2890,
    distance: 1.5,
    priceLevel: 1,
    isOpen: true,
    address: "Banjara Hills, Hyderabad",
    description: "Chutneys is a beloved South Indian restaurant famous for its wide variety of dosas, idlis, and unique chutneys. A must-visit for vegetarian food lovers in Hyderabad.",
    bestTimeToVisit: "8:00 AM - 10:30 AM",
    recommendedFor: ["Family", "Parents", "Solo"],
    tags: ["South Indian", "Vegetarian", "Dosa", "Breakfast"],
    mood: ["chill", "peaceful", "budget"],
    companion: ["family", "parents", "solo"],
    photos: [RESTAURANT_IMAGES[2], RESTAURANT_IMAGES[3], RESTAURANT_IMAGES[9]],
    reviews: [
      { id: "r4", user: "Priya S.", rating: 5, text: "Best dosas in Hyderabad! The cheese dosa and filter coffee are heavenly.", date: "5 days ago" },
    ],
    lat: 17.388,
    lng: 78.4897,
    trending: true,
  },
  {
    id: "restaurants_4",
    name: "Ohri's Jiva Imperia",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "restaurant",
    cuisine: "Multi-Cuisine",
    image: RESTAURANT_IMAGES[3],
    rating: 4.4,
    reviewCount: 1560,
    distance: 3.1,
    priceLevel: 2,
    isOpen: true,
    address: "Banjara Hills Road No. 1, Hyderabad",
    description: "Ohri's Jiva Imperia offers a premium fine dining experience with multi-cuisine options and a stunning rooftop view of the city. Perfect for special occasions.",
    bestTimeToVisit: "7:00 PM - 10:00 PM",
    recommendedFor: ["Couples", "Date Night", "Special Occasions"],
    tags: ["Fine Dining", "Multi-Cuisine", "Rooftop", "Upscale"],
    mood: ["romantic", "chill"],
    companion: ["girlfriend", "boyfriend"],
    photos: [RESTAURANT_IMAGES[3], RESTAURANT_IMAGES[5], RESTAURANT_IMAGES[4]],
    reviews: [
      { id: "r5", user: "Anita R.", rating: 5, text: "Perfect place for a romantic dinner. The ambiance is unmatched in Hyderabad.", date: "1 week ago" },
    ],
    lat: 17.389,
    lng: 78.4907,
  },
  {
    id: "restaurants_5",
    name: "Bawarchi",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "restaurant",
    cuisine: "Hyderabadi",
    image: RESTAURANT_IMAGES[4],
    rating: 4.0,
    reviewCount: 3780,
    distance: 2.0,
    priceLevel: 3,
    isOpen: true,
    address: "RTC Cross Roads, Hyderabad",
    description: "Bawarchi is a Hyderabadi legend serving some of the most flavorful biryani in the city. Known for its generous portions and affordable prices, it is a favorite among locals.",
    bestTimeToVisit: "1:00 PM - 3:00 PM",
    recommendedFor: ["Friends", "College Groups", "Solo"],
    tags: ["Biryani", "Budget Friendly", "Local Favorite", "Non-Veg"],
    mood: ["fun", "budget"],
    companion: ["friends", "college", "solo"],
    photos: [RESTAURANT_IMAGES[4], RESTAURANT_IMAGES[0], RESTAURANT_IMAGES[7]],
    reviews: [
      { id: "r6", user: "Varun D.", rating: 4, text: "Great value for money. The chicken biryani is incredible.", date: "4 days ago" },
    ],
    lat: 17.39,
    lng: 78.4917,
  },
  {
    id: "restaurants_6",
    name: "Pista House",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "restaurant",
    cuisine: "Hyderabadi",
    image: RESTAURANT_IMAGES[5],
    rating: 4.1,
    reviewCount: 2450,
    distance: 1.8,
    priceLevel: 1,
    isOpen: true,
    address: "Charminar, Hyderabad",
    description: "Pista House near Charminar is famous for its award-winning haleem and delicious Hyderabadi snacks. A cultural food landmark of the old city.",
    bestTimeToVisit: "5:00 PM - 8:00 PM",
    recommendedFor: ["Solo", "Friends", "Tourists"],
    tags: ["Haleem", "Hyderabadi", "Old City", "Budget"],
    mood: ["chill", "adventure", "budget"],
    companion: ["friends", "solo", "college"],
    photos: [RESTAURANT_IMAGES[5], RESTAURANT_IMAGES[8], RESTAURANT_IMAGES[6]],
    reviews: [
      { id: "r7", user: "Faizan A.", rating: 5, text: "The haleem here has won the best haleem award multiple times. Truly deserved!", date: "2 days ago" },
    ],
    lat: 17.391,
    lng: 78.4927,
  },
  {
    id: "restaurants_7",
    name: "AB's Absolute Barbecues",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "restaurant",
    cuisine: "Barbecue",
    image: RESTAURANT_IMAGES[6],
    rating: 4.2,
    reviewCount: 2100,
    distance: 4.2,
    priceLevel: 2,
    isOpen: true,
    address: "Jubilee Hills, Hyderabad",
    description: "AB's Absolute Barbecues is a popular grill and buffet restaurant with live cooking stations, unlimited starters, and an energetic atmosphere perfect for group dining.",
    bestTimeToVisit: "7:00 PM - 9:30 PM",
    recommendedFor: ["Friends", "Family", "Birthday"],
    tags: ["Barbecue", "Buffet", "Unlimited", "Grill"],
    mood: ["fun", "chill"],
    companion: ["friends", "family", "college"],
    photos: [RESTAURANT_IMAGES[6], RESTAURANT_IMAGES[8], RESTAURANT_IMAGES[3]],
    reviews: [
      { id: "r8", user: "Divya N.", rating: 4, text: "Amazing buffet spread! The live grill section is fantastic.", date: "1 week ago" },
    ],
    lat: 17.392,
    lng: 78.4937,
  },
  {
    id: "restaurants_8",
    name: "Olive Bistro",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "restaurant",
    cuisine: "Mediterranean",
    image: RESTAURANT_IMAGES[7],
    rating: 4.3,
    reviewCount: 980,
    distance: 5.5,
    priceLevel: 3,
    isOpen: true,
    address: "Durgam Cheruvu Road, Hyderabad",
    description: "Olive Bistro offers a stunning lakeside Mediterranean dining experience with beautiful interiors, craft cocktails, and a menu inspired by European cuisine.",
    bestTimeToVisit: "6:00 PM - 9:00 PM",
    recommendedFor: ["Couples", "Date Night", "Special Occasions"],
    tags: ["Mediterranean", "Lakeside", "Upscale", "Cocktails"],
    mood: ["romantic", "peaceful", "chill"],
    companion: ["girlfriend", "boyfriend"],
    photos: [RESTAURANT_IMAGES[7], RESTAURANT_IMAGES[3], RESTAURANT_IMAGES[9]],
    reviews: [
      { id: "r9", user: "Meera J.", rating: 5, text: "The lakeside view at sunset is magical. Perfect date spot.", date: "3 days ago" },
    ],
    lat: 17.393,
    lng: 78.4947,
    trending: true,
  },
  {
    id: "restaurants_9",
    name: "Barbeque Nation",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "restaurant",
    cuisine: "Barbecue",
    image: RESTAURANT_IMAGES[8],
    rating: 4.4,
    reviewCount: 3450,
    distance: 2.3,
    priceLevel: 1,
    isOpen: true,
    address: "GVK One Mall, Banjara Hills, Hyderabad",
    description: "Barbeque Nation brings the fun of tableside grilling with an extensive buffet spread. The kulfi desserts and live counters make it a family favorite.",
    bestTimeToVisit: "7:30 PM - 9:30 PM",
    recommendedFor: ["Family", "Friends", "Birthday"],
    tags: ["BBQ", "Buffet", "Family", "Live Grill"],
    mood: ["fun", "chill"],
    companion: ["family", "friends", "parents"],
    photos: [RESTAURANT_IMAGES[8], RESTAURANT_IMAGES[6], RESTAURANT_IMAGES[4]],
    reviews: [
      { id: "r10", user: "Kiran T.", rating: 4, text: "Great value buffet! Kids love the live grilling at the table.", date: "5 days ago" },
    ],
    lat: 17.394,
    lng: 78.4957,
    sponsored: true,
  },
  {
    id: "restaurants_10",
    name: "Exotica",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "restaurant",
    cuisine: "Multi-Cuisine",
    image: RESTAURANT_IMAGES[9],
    rating: 4.0,
    reviewCount: 1230,
    distance: 3.5,
    priceLevel: 2,
    isOpen: true,
    address: "Kondapur, Hyderabad",
    description: "Exotica is a vibrant multi-cuisine restaurant with a lively party atmosphere, DJ nights, and an extensive menu ranging from Indian to Continental.",
    bestTimeToVisit: "8:00 PM - 11:00 PM",
    recommendedFor: ["Friends", "College Groups", "Parties"],
    tags: ["Multi-Cuisine", "Party", "DJ", "Nightlife"],
    mood: ["fun", "adventure"],
    companion: ["friends", "college"],
    photos: [RESTAURANT_IMAGES[9], RESTAURANT_IMAGES[1], RESTAURANT_IMAGES[5]],
    reviews: [
      { id: "r11", user: "Rahul S.", rating: 4, text: "Great music and food combo! Perfect for a night out with friends.", date: "6 days ago" },
    ],
    lat: 17.395,
    lng: 78.4967,
  },
  {
    id: "cafes_1",
    name: "Roastery Coffee House",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "cafe",
    cuisine: "Coffee & Snacks",
    image: CAFE_IMAGES[0],
    rating: 4.1,
    reviewCount: 1450,
    distance: 1.3,
    priceLevel: 2,
    isOpen: true,
    address: "Jubilee Hills, Hyderabad",
    description: "Roastery Coffee House is a specialty coffee destination with artisan brews, fresh pastries, and a warm industrial-chic vibe. Perfect for remote work or a relaxed catch-up.",
    bestTimeToVisit: "10:00 AM - 12:00 PM",
    recommendedFor: ["Solo", "Couples", "Remote Workers"],
    tags: ["Coffee", "Artisan", "Cozy", "Wi-Fi"],
    mood: ["peaceful", "chill", "romantic"],
    companion: ["solo", "girlfriend", "boyfriend"],
    photos: [CAFE_IMAGES[0], CAFE_IMAGES[2], CAFE_IMAGES[8]],
    reviews: [
      { id: "r12", user: "Aditi V.", rating: 5, text: "Best specialty coffee in Hyderabad. The cold brew is incredible!", date: "1 day ago" },
    ],
    lat: 17.386,
    lng: 78.4877,
    trending: true,
  },
  {
    id: "cafes_2",
    name: "Concu",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "cafe",
    cuisine: "Bakery & Desserts",
    image: CAFE_IMAGES[1],
    rating: 4.2,
    reviewCount: 2100,
    distance: 2.1,
    priceLevel: 3,
    isOpen: true,
    address: "Banjara Hills, Hyderabad",
    description: "Concu is Hyderabad's finest European-style bakery and patisserie, known for its artisanal breads, handcrafted pastries, and Instagram-worthy desserts.",
    bestTimeToVisit: "3:00 PM - 6:00 PM",
    recommendedFor: ["Couples", "Friends", "Dessert Lovers"],
    tags: ["Bakery", "Desserts", "European", "Pastries"],
    mood: ["romantic", "chill", "peaceful"],
    companion: ["girlfriend", "boyfriend", "friends"],
    photos: [CAFE_IMAGES[1], CAFE_IMAGES[4], CAFE_IMAGES[7]],
    reviews: [
      { id: "r13", user: "Nisha R.", rating: 5, text: "The croissants here are Paris-level good. Absolute must visit!", date: "3 days ago" },
    ],
    lat: 17.387,
    lng: 78.4887,
  },
  {
    id: "cafes_3",
    name: "Autumn Leaf Cafe",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "cafe",
    cuisine: "Continental",
    image: CAFE_IMAGES[2],
    rating: 4.3,
    reviewCount: 890,
    distance: 1.0,
    priceLevel: 1,
    isOpen: true,
    address: "Kondapur, Hyderabad",
    description: "Autumn Leaf Cafe is a charming neighborhood cafe with a rustic garden setting, serving fresh salads, wraps, and some of the best brewed coffee in the IT corridor.",
    bestTimeToVisit: "9:00 AM - 11:00 AM",
    recommendedFor: ["Solo", "Friends", "Students"],
    tags: ["Garden", "Budget", "Continental", "Cozy"],
    mood: ["peaceful", "chill", "budget"],
    companion: ["solo", "friends", "college"],
    photos: [CAFE_IMAGES[2], CAFE_IMAGES[5], CAFE_IMAGES[9]],
    reviews: [
      { id: "r14", user: "Sai K.", rating: 4, text: "Love the garden seating! Great place to study or read a book.", date: "1 week ago" },
    ],
    lat: 17.388,
    lng: 78.4897,
  },
  {
    id: "cafes_4",
    name: "The Gallery Cafe",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "cafe",
    cuisine: "Continental",
    image: CAFE_IMAGES[3],
    rating: 4.4,
    reviewCount: 760,
    distance: 2.5,
    priceLevel: 2,
    isOpen: true,
    address: "Banjara Hills Road No. 10, Hyderabad",
    description: "The Gallery Cafe combines art and cuisine beautifully. With rotating art exhibitions on its walls and a creative menu, it is a cultural experience as much as a culinary one.",
    bestTimeToVisit: "4:00 PM - 7:00 PM",
    recommendedFor: ["Couples", "Solo", "Art Lovers"],
    tags: ["Art", "Gallery", "Continental", "Creative"],
    mood: ["peaceful", "romantic", "chill"],
    companion: ["girlfriend", "boyfriend", "solo"],
    photos: [CAFE_IMAGES[3], CAFE_IMAGES[6], CAFE_IMAGES[0]],
    reviews: [
      { id: "r15", user: "Tanvi M.", rating: 5, text: "A hidden gem! The art on the walls changes every month. Beautiful space.", date: "4 days ago" },
    ],
    lat: 17.389,
    lng: 78.4907,
    trending: true,
  },
  {
    id: "cafes_5",
    name: "Theory Cafe",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "cafe",
    cuisine: "Coffee & Light Bites",
    image: CAFE_IMAGES[4],
    rating: 4.0,
    reviewCount: 560,
    distance: 3.8,
    priceLevel: 3,
    isOpen: true,
    address: "Gachibowli, Hyderabad",
    description: "Theory Cafe is a trendy co-working cafe popular with tech professionals. With fast Wi-Fi, power outlets at every table, and great coffee, it is a productivity paradise.",
    bestTimeToVisit: "10:00 AM - 4:00 PM",
    recommendedFor: ["Solo", "Remote Workers", "Students"],
    tags: ["Co-Working", "Wi-Fi", "Tech", "Coffee"],
    mood: ["peaceful", "chill"],
    companion: ["solo", "college"],
    photos: [CAFE_IMAGES[4], CAFE_IMAGES[8], CAFE_IMAGES[1]],
    reviews: [
      { id: "r16", user: "Amit B.", rating: 4, text: "Perfect for working remotely. The cold coffee is great.", date: "2 weeks ago" },
    ],
    lat: 17.39,
    lng: 78.4917,
  },
  {
    id: "cafes_6",
    name: "Cafe Niloufer",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "cafe",
    cuisine: "Tea & Snacks",
    image: CAFE_IMAGES[5],
    rating: 4.1,
    reviewCount: 5200,
    distance: 0.8,
    priceLevel: 1,
    isOpen: true,
    address: "Lakdikapul, Hyderabad",
    description: "Cafe Niloufer is an iconic Hyderabadi tea stall famous for its Irani chai, Osmania biscuits, and bun maska. A true Hyderabadi experience that runs 24/7.",
    bestTimeToVisit: "6:00 AM - 9:00 AM",
    recommendedFor: ["Solo", "Friends", "Tourists"],
    tags: ["Irani Chai", "Budget", "Iconic", "24/7"],
    mood: ["chill", "budget", "adventure"],
    companion: ["friends", "solo", "college"],
    photos: [CAFE_IMAGES[5], CAFE_IMAGES[9], CAFE_IMAGES[2]],
    reviews: [
      { id: "r17", user: "Deepak L.", rating: 5, text: "The Irani chai here is legendary. Open 24 hours, always packed!", date: "1 day ago" },
    ],
    lat: 17.391,
    lng: 78.4927,
    trending: true,
  },
  {
    id: "cafes_7",
    name: "Heart Cup Coffee",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "cafe",
    cuisine: "Coffee & Brunch",
    image: CAFE_IMAGES[6],
    rating: 4.2,
    reviewCount: 1890,
    distance: 2.7,
    priceLevel: 2,
    isOpen: true,
    address: "Hitech City, Hyderabad",
    description: "Heart Cup Coffee is a multi-level cafe with rooftop seating, live music evenings, and an extensive brunch menu. A popular hangout for the young crowd in Hitech City.",
    bestTimeToVisit: "5:00 PM - 8:00 PM",
    recommendedFor: ["Friends", "College Groups", "Date Night"],
    tags: ["Rooftop", "Live Music", "Brunch", "Hangout"],
    mood: ["fun", "chill", "romantic"],
    companion: ["friends", "college", "girlfriend", "boyfriend"],
    photos: [CAFE_IMAGES[6], CAFE_IMAGES[3], CAFE_IMAGES[7]],
    reviews: [
      { id: "r18", user: "Shweta G.", rating: 4, text: "Love the rooftop vibes! Live music on weekends is awesome.", date: "5 days ago" },
    ],
    lat: 17.392,
    lng: 78.4937,
  },
  {
    id: "cafes_8",
    name: "Coffee Cup",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "cafe",
    cuisine: "Coffee & Snacks",
    image: CAFE_IMAGES[7],
    rating: 4.3,
    reviewCount: 670,
    distance: 4.0,
    priceLevel: 3,
    isOpen: true,
    address: "Madhapur, Hyderabad",
    description: "Coffee Cup is a cozy neighborhood cafe known for its hand-poured coffees and freshly baked goods. A quiet escape from the busy Madhapur tech corridor.",
    bestTimeToVisit: "3:00 PM - 5:00 PM",
    recommendedFor: ["Solo", "Couples"],
    tags: ["Hand-Poured", "Bakery", "Quiet", "Cozy"],
    mood: ["peaceful", "chill"],
    companion: ["solo", "girlfriend", "boyfriend"],
    photos: [CAFE_IMAGES[7], CAFE_IMAGES[0], CAFE_IMAGES[4]],
    reviews: [
      { id: "r19", user: "Lakshmi P.", rating: 5, text: "Such a peaceful spot. The pour-over coffee is exceptional.", date: "1 week ago" },
    ],
    lat: 17.393,
    lng: 78.4947,
  },
  {
    id: "cafes_9",
    name: "Last House Coffee",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "cafe",
    cuisine: "Coffee & Books",
    image: CAFE_IMAGES[8],
    rating: 4.4,
    reviewCount: 430,
    distance: 1.6,
    priceLevel: 1,
    isOpen: true,
    address: "Film Nagar, Hyderabad",
    description: "Last House Coffee is a book lover's paradise with walls lined with books, cozy reading nooks, and carefully crafted beverages. Borrow, read, and sip in peace.",
    bestTimeToVisit: "2:00 PM - 6:00 PM",
    recommendedFor: ["Solo", "Students", "Bookworms"],
    tags: ["Books", "Cozy", "Budget", "Reading"],
    mood: ["peaceful", "chill", "budget"],
    companion: ["solo", "college"],
    photos: [CAFE_IMAGES[8], CAFE_IMAGES[5], CAFE_IMAGES[1]],
    reviews: [
      { id: "r20", user: "Rohit C.", rating: 5, text: "A bookworm's dream! Great chai, great books, great vibes.", date: "3 days ago" },
    ],
    lat: 17.394,
    lng: 78.4957,
  },
  {
    id: "cafes_10",
    name: "Le Vantage Cafe Bar",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "cafe",
    cuisine: "European",
    image: CAFE_IMAGES[9],
    rating: 4.0,
    reviewCount: 780,
    distance: 3.2,
    priceLevel: 2,
    isOpen: true,
    address: "Jubilee Hills, Hyderabad",
    description: "Le Vantage is an upscale cafe-bar with panoramic views, European-inspired menu, and craft cocktails. The terrace seating at sunset is unforgettable.",
    bestTimeToVisit: "5:00 PM - 9:00 PM",
    recommendedFor: ["Couples", "Friends", "Special Occasions"],
    tags: ["Terrace", "Views", "European", "Cocktails"],
    mood: ["romantic", "chill"],
    companion: ["girlfriend", "boyfriend", "friends"],
    photos: [CAFE_IMAGES[9], CAFE_IMAGES[3], CAFE_IMAGES[6]],
    reviews: [
      { id: "r21", user: "Kavya I.", rating: 4, text: "Stunning views from the terrace! The cocktails are well-crafted.", date: "1 week ago" },
    ],
    lat: 17.395,
    lng: 78.4967,
    sponsored: true,
  },
  {
    id: "adventure_1",
    name: "Wonderla Hyderabad",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "adventure",
    image: ADVENTURE_IMAGES[0],
    rating: 4.1,
    reviewCount: 6200,
    distance: 8.5,
    priceLevel: 2,
    isOpen: true,
    address: "Raviryal, Hyderabad",
    description: "Wonderla is India's premier amusement park with thrilling roller coasters, water rides, and a wave pool. A full day of excitement for all ages.",
    bestTimeToVisit: "10:00 AM - 4:00 PM",
    recommendedFor: ["Family", "Friends", "College Groups"],
    tags: ["Amusement Park", "Water Rides", "Thrilling", "Day Out"],
    mood: ["fun", "adventure"],
    companion: ["friends", "family", "college"],
    photos: [ADVENTURE_IMAGES[0], ADVENTURE_IMAGES[4], ADVENTURE_IMAGES[9]],
    reviews: [
      { id: "r22", user: "Vikram H.", rating: 4, text: "Best amusement park in South India! The Recoil ride is insane.", date: "2 days ago" },
    ],
    lat: 17.386,
    lng: 78.4877,
    trending: true,
  },
  {
    id: "adventure_2",
    name: "Ramoji Film City",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "adventure",
    image: ADVENTURE_IMAGES[1],
    rating: 4.2,
    reviewCount: 8900,
    distance: 12.0,
    priceLevel: 3,
    isOpen: true,
    address: "Ramoji Film City, Abdullapurmet, Hyderabad",
    description: "Ramoji Film City is the world's largest integrated film studio complex. Explore movie sets, enjoy live shows, adventure activities, and get a behind-the-scenes look at filmmaking.",
    bestTimeToVisit: "9:00 AM - 5:00 PM",
    recommendedFor: ["Family", "Friends", "Tourists"],
    tags: ["Film City", "Studio", "Shows", "Entertainment"],
    mood: ["fun", "adventure", "chill"],
    companion: ["family", "friends", "parents"],
    photos: [ADVENTURE_IMAGES[1], ADVENTURE_IMAGES[3], ADVENTURE_IMAGES[5]],
    reviews: [
      { id: "r23", user: "Sunita B.", rating: 5, text: "A whole day is not enough! So many things to see and do here.", date: "4 days ago" },
    ],
    lat: 17.387,
    lng: 78.4887,
    sponsored: true,
  },
  {
    id: "adventure_3",
    name: "Ocean Park",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "adventure",
    image: ADVENTURE_IMAGES[2],
    rating: 4.3,
    reviewCount: 2340,
    distance: 6.0,
    priceLevel: 1,
    isOpen: true,
    address: "Gandipet Road, Hyderabad",
    description: "Ocean Park is a popular water park with thrilling slides, a lazy river, and rain dance area. An affordable family fun spot, especially great during summer.",
    bestTimeToVisit: "11:00 AM - 3:00 PM",
    recommendedFor: ["Family", "Friends", "Kids"],
    tags: ["Water Park", "Slides", "Summer", "Budget"],
    mood: ["fun", "adventure", "budget"],
    companion: ["friends", "family", "college"],
    photos: [ADVENTURE_IMAGES[2], ADVENTURE_IMAGES[6], ADVENTURE_IMAGES[0]],
    reviews: [
      { id: "r24", user: "Neha W.", rating: 4, text: "Kids had an absolute blast! Good budget option for water fun.", date: "1 week ago" },
    ],
    lat: 17.388,
    lng: 78.4897,
  },
  {
    id: "adventure_4",
    name: "Mount Opera",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "adventure",
    image: ADVENTURE_IMAGES[3],
    rating: 4.4,
    reviewCount: 1780,
    distance: 9.2,
    priceLevel: 2,
    isOpen: true,
    address: "Near Ramoji Film City, Hyderabad",
    description: "Mount Opera is a resort-style adventure park with a mix of water rides, amusement activities, camping grounds, and a beautiful hilltop setting for overnight stays.",
    bestTimeToVisit: "10:00 AM - 6:00 PM",
    recommendedFor: ["Friends", "College Groups", "Family"],
    tags: ["Resort", "Camping", "Water Rides", "Adventure"],
    mood: ["adventure", "fun"],
    companion: ["friends", "college", "family"],
    photos: [ADVENTURE_IMAGES[3], ADVENTURE_IMAGES[7], ADVENTURE_IMAGES[1]],
    reviews: [
      { id: "r25", user: "Aditya G.", rating: 5, text: "Camping under the stars was amazing! Great adventure park.", date: "5 days ago" },
    ],
    lat: 17.389,
    lng: 78.4907,
  },
  {
    id: "adventure_5",
    name: "Ananthagiri Hills",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "adventure",
    image: ADVENTURE_IMAGES[4],
    rating: 4.0,
    reviewCount: 3450,
    distance: 15.0,
    priceLevel: 3,
    isOpen: true,
    address: "Vikarabad District, near Hyderabad",
    description: "Ananthagiri Hills is a serene hill station near Hyderabad with trekking trails, ancient temples, waterfalls, and lush green forests. A perfect weekend escape.",
    bestTimeToVisit: "6:00 AM - 10:00 AM",
    recommendedFor: ["Couples", "Trekkers", "Nature Lovers"],
    tags: ["Hills", "Trekking", "Nature", "Weekend Trip"],
    mood: ["adventure", "peaceful"],
    companion: ["friends", "girlfriend", "boyfriend", "solo"],
    photos: [ADVENTURE_IMAGES[4], ADVENTURE_IMAGES[8], ADVENTURE_IMAGES[2]],
    reviews: [
      { id: "r26", user: "Pooja D.", rating: 4, text: "Beautiful trek through the forest. The waterfall at the end is magical!", date: "3 days ago" },
    ],
    lat: 17.39,
    lng: 78.4917,
  },
  {
    id: "adventure_6",
    name: "Necklace Road",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "adventure",
    image: ADVENTURE_IMAGES[5],
    rating: 4.1,
    reviewCount: 4560,
    distance: 1.5,
    priceLevel: 1,
    isOpen: true,
    address: "Necklace Road, Hussain Sagar, Hyderabad",
    description: "Necklace Road along Hussain Sagar Lake is Hyderabad's favorite evening hangout with cycling tracks, street food, boat rides, and stunning sunset views.",
    bestTimeToVisit: "5:00 PM - 8:00 PM",
    recommendedFor: ["Everyone", "Families", "Couples"],
    tags: ["Lake", "Cycling", "Sunset", "Street Food"],
    mood: ["chill", "romantic", "peaceful", "budget"],
    companion: ["friends", "family", "girlfriend", "boyfriend", "solo"],
    photos: [ADVENTURE_IMAGES[5], ADVENTURE_IMAGES[9], ADVENTURE_IMAGES[3]],
    reviews: [
      { id: "r27", user: "Harsha M.", rating: 5, text: "Best sunset spot in Hyderabad! Love cycling here in the evenings.", date: "1 day ago" },
    ],
    lat: 17.391,
    lng: 78.4927,
    trending: true,
  },
  {
    id: "adventure_7",
    name: "Hussain Sagar Lake",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "adventure",
    image: ADVENTURE_IMAGES[6],
    rating: 4.2,
    reviewCount: 5670,
    distance: 1.8,
    priceLevel: 2,
    isOpen: true,
    address: "Hussain Sagar, Hyderabad",
    description: "Hussain Sagar is the heart of Hyderabad, featuring boat rides to the iconic Buddha statue, the Lumbini Park light show, and a beautiful promenade for evening walks.",
    bestTimeToVisit: "4:00 PM - 7:00 PM",
    recommendedFor: ["Tourists", "Family", "Couples"],
    tags: ["Lake", "Boat Ride", "Buddha Statue", "Landmark"],
    mood: ["chill", "peaceful", "romantic"],
    companion: ["family", "girlfriend", "boyfriend", "friends", "solo"],
    photos: [ADVENTURE_IMAGES[6], ADVENTURE_IMAGES[0], ADVENTURE_IMAGES[5]],
    reviews: [
      { id: "r28", user: "Rajesh N.", rating: 4, text: "The boat ride to the Buddha statue is a must-do in Hyderabad.", date: "2 days ago" },
    ],
    lat: 17.392,
    lng: 78.4937,
  },
  {
    id: "adventure_8",
    name: "Shamirpet Lake",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "adventure",
    image: ADVENTURE_IMAGES[7],
    rating: 4.3,
    reviewCount: 890,
    distance: 10.5,
    priceLevel: 3,
    isOpen: true,
    address: "Shamirpet, Hyderabad",
    description: "Shamirpet Lake is a tranquil getaway surrounded by a deer park and lush greenery. Perfect for picnics, bird watching, and escaping the city bustle.",
    bestTimeToVisit: "7:00 AM - 11:00 AM",
    recommendedFor: ["Nature Lovers", "Families", "Photographers"],
    tags: ["Lake", "Deer Park", "Birds", "Picnic"],
    mood: ["peaceful", "chill"],
    companion: ["family", "solo", "friends"],
    photos: [ADVENTURE_IMAGES[7], ADVENTURE_IMAGES[4], ADVENTURE_IMAGES[8]],
    reviews: [
      { id: "r29", user: "Maya T.", rating: 5, text: "Such a peaceful place. Spotted so many bird species here!", date: "1 week ago" },
    ],
    lat: 17.393,
    lng: 78.4947,
  },
  {
    id: "adventure_9",
    name: "KBR National Park",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "adventure",
    image: ADVENTURE_IMAGES[8],
    rating: 4.4,
    reviewCount: 3890,
    distance: 2.2,
    priceLevel: 1,
    isOpen: true,
    address: "Jubilee Hills, Hyderabad",
    description: "KBR National Park is a green lung in the heart of the city. With walking trails, jogging tracks, and rich biodiversity, it is the best free nature experience in Hyderabad.",
    bestTimeToVisit: "5:30 AM - 8:00 AM",
    recommendedFor: ["Joggers", "Nature Lovers", "Solo"],
    tags: ["Park", "Jogging", "Nature", "Free Entry"],
    mood: ["peaceful", "chill", "adventure", "budget"],
    companion: ["solo", "friends"],
    photos: [ADVENTURE_IMAGES[8], ADVENTURE_IMAGES[5], ADVENTURE_IMAGES[9]],
    reviews: [
      { id: "r30", user: "Suresh V.", rating: 5, text: "My daily morning jog here keeps me sane. Beautiful biodiversity.", date: "2 days ago" },
    ],
    lat: 17.394,
    lng: 78.4957,
    trending: true,
  },
  {
    id: "adventure_10",
    name: "District Gravity",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "adventure",
    image: ADVENTURE_IMAGES[9],
    rating: 4.0,
    reviewCount: 1120,
    distance: 4.5,
    priceLevel: 2,
    isOpen: true,
    address: "Gachibowli, Hyderabad",
    description: "District Gravity is an indoor adventure park with trampolines, rock climbing walls, ninja courses, and VR experiences. A high-energy spot for thrill-seekers of all ages.",
    bestTimeToVisit: "4:00 PM - 8:00 PM",
    recommendedFor: ["Friends", "College Groups", "Kids"],
    tags: ["Trampoline", "Rock Climbing", "Indoor", "VR"],
    mood: ["fun", "adventure"],
    companion: ["friends", "college", "family"],
    photos: [ADVENTURE_IMAGES[9], ADVENTURE_IMAGES[1], ADVENTURE_IMAGES[6]],
    reviews: [
      { id: "r31", user: "Akhil J.", rating: 4, text: "The ninja course is so much fun! Great place for a group outing.", date: "4 days ago" },
    ],
    lat: 17.395,
    lng: 78.4967,
  },
  {
    id: "entertainment_1",
    name: "Prasads Multiplex",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "entertainment",
    image: ENTERTAINMENT_IMAGES[0],
    rating: 4.1,
    reviewCount: 7800,
    distance: 1.4,
    priceLevel: 2,
    isOpen: true,
    address: "Necklace Road, Hyderabad",
    description: "Prasads is Hyderabad's most iconic multiplex with an IMAX screen, food court, gaming zone, and shopping. The IMAX experience here is one of the best in India.",
    bestTimeToVisit: "6:00 PM - 10:00 PM",
    recommendedFor: ["Friends", "Family", "Movie Lovers"],
    tags: ["IMAX", "Cinema", "Gaming", "Food Court"],
    mood: ["fun", "chill"],
    companion: ["friends", "family", "college"],
    photos: [ENTERTAINMENT_IMAGES[0], ENTERTAINMENT_IMAGES[3], ENTERTAINMENT_IMAGES[5]],
    reviews: [
      { id: "r32", user: "Naveen A.", rating: 5, text: "The IMAX screen is massive! Best cinema experience in Hyderabad.", date: "1 day ago" },
    ],
    lat: 17.386,
    lng: 78.4877,
    trending: true,
  },
  {
    id: "entertainment_2",
    name: "AMB Cinemas",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "entertainment",
    image: ENTERTAINMENT_IMAGES[1],
    rating: 4.2,
    reviewCount: 4500,
    distance: 3.5,
    priceLevel: 3,
    isOpen: true,
    address: "Gachibowli, Hyderabad",
    description: "AMB Cinemas by Mahesh Babu offers a luxury movie experience with premium seating, Dolby Atmos, gourmet dining, and a stunning lobby. A premium entertainment destination.",
    bestTimeToVisit: "7:00 PM - 10:00 PM",
    recommendedFor: ["Couples", "Movie Lovers", "Premium Experience"],
    tags: ["Luxury Cinema", "Dolby Atmos", "Premium", "Gourmet"],
    mood: ["romantic", "chill"],
    companion: ["girlfriend", "boyfriend", "friends"],
    photos: [ENTERTAINMENT_IMAGES[1], ENTERTAINMENT_IMAGES[4], ENTERTAINMENT_IMAGES[8]],
    reviews: [
      { id: "r33", user: "Sravani K.", rating: 5, text: "Hands down the best cinema in India. The recliner seats are heavenly!", date: "3 days ago" },
    ],
    lat: 17.387,
    lng: 78.4887,
    sponsored: true,
  },
  {
    id: "entertainment_3",
    name: "PVR Cinemas",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "entertainment",
    image: ENTERTAINMENT_IMAGES[2],
    rating: 4.3,
    reviewCount: 5600,
    distance: 2.0,
    priceLevel: 1,
    isOpen: true,
    address: "Forum Sujana Mall, Kukatpally, Hyderabad",
    description: "PVR Cinemas at Forum Mall offers an accessible movie experience with multiple screens, affordable tickets, and a wide selection of snacks and beverages.",
    bestTimeToVisit: "3:00 PM - 9:00 PM",
    recommendedFor: ["Family", "Friends", "Budget Movie Night"],
    tags: ["Cinema", "Affordable", "Family", "Mall"],
    mood: ["fun", "chill", "budget"],
    companion: ["friends", "family", "college"],
    photos: [ENTERTAINMENT_IMAGES[2], ENTERTAINMENT_IMAGES[6], ENTERTAINMENT_IMAGES[0]],
    reviews: [
      { id: "r34", user: "Prasad G.", rating: 4, text: "Good value for money. Always catch the latest releases here.", date: "5 days ago" },
    ],
    lat: 17.388,
    lng: 78.4897,
  },
  {
    id: "entertainment_4",
    name: "Smaaash",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "entertainment",
    image: ENTERTAINMENT_IMAGES[3],
    rating: 4.4,
    reviewCount: 2340,
    distance: 2.8,
    priceLevel: 2,
    isOpen: true,
    address: "Inorbit Mall, Madhapur, Hyderabad",
    description: "Smaaash is an indoor entertainment center with VR gaming, bowling, go-karting, cricket simulators, and a sports bar. The ultimate hangout for gaming enthusiasts.",
    bestTimeToVisit: "4:00 PM - 9:00 PM",
    recommendedFor: ["Friends", "College Groups", "Date Night"],
    tags: ["Gaming", "VR", "Bowling", "Go-Kart"],
    mood: ["fun", "adventure"],
    companion: ["friends", "college", "girlfriend", "boyfriend"],
    photos: [ENTERTAINMENT_IMAGES[3], ENTERTAINMENT_IMAGES[7], ENTERTAINMENT_IMAGES[1]],
    reviews: [
      { id: "r35", user: "Venu M.", rating: 5, text: "The VR experiences are incredible! Go-karting is a must try.", date: "2 days ago" },
    ],
    lat: 17.389,
    lng: 78.4907,
    trending: true,
  },
  {
    id: "entertainment_5",
    name: "Lazer Ops",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "entertainment",
    image: ENTERTAINMENT_IMAGES[4],
    rating: 4.0,
    reviewCount: 980,
    distance: 3.0,
    priceLevel: 3,
    isOpen: true,
    address: "Jubilee Hills, Hyderabad",
    description: "Lazer Ops offers immersive laser tag battles in themed arenas with fog effects, strategic obstacles, and competitive gameplay. Great for team-building events.",
    bestTimeToVisit: "5:00 PM - 9:00 PM",
    recommendedFor: ["Friends", "College Groups", "Team Events"],
    tags: ["Laser Tag", "Team Building", "Indoor", "Competitive"],
    mood: ["fun", "adventure"],
    companion: ["friends", "college"],
    photos: [ENTERTAINMENT_IMAGES[4], ENTERTAINMENT_IMAGES[9], ENTERTAINMENT_IMAGES[2]],
    reviews: [
      { id: "r36", user: "Chaitanya R.", rating: 4, text: "Super fun! The themed arena makes it feel like a real battle.", date: "1 week ago" },
    ],
    lat: 17.39,
    lng: 78.4917,
  },
  {
    id: "entertainment_6",
    name: "Mystery Rooms",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "entertainment",
    image: ENTERTAINMENT_IMAGES[5],
    rating: 4.1,
    reviewCount: 1560,
    distance: 2.4,
    priceLevel: 1,
    isOpen: true,
    address: "Begumpet, Hyderabad",
    description: "Mystery Rooms is an escape room experience with challenging puzzles, mysterious themes, and a 60-minute countdown. Test your wits with friends in themed rooms.",
    bestTimeToVisit: "3:00 PM - 8:00 PM",
    recommendedFor: ["Friends", "Couples", "Team Building"],
    tags: ["Escape Room", "Puzzles", "Mystery", "Team Work"],
    mood: ["adventure", "fun"],
    companion: ["friends", "college", "girlfriend", "boyfriend"],
    photos: [ENTERTAINMENT_IMAGES[5], ENTERTAINMENT_IMAGES[8], ENTERTAINMENT_IMAGES[3]],
    reviews: [
      { id: "r37", user: "Ananya S.", rating: 5, text: "Best escape room in Hyderabad! The horror theme was spine-chilling.", date: "4 days ago" },
    ],
    lat: 17.391,
    lng: 78.4927,
  },
  {
    id: "entertainment_7",
    name: "Sky Zone Hyderabad",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "entertainment",
    image: ENTERTAINMENT_IMAGES[6],
    rating: 4.2,
    reviewCount: 1890,
    distance: 3.8,
    priceLevel: 2,
    isOpen: true,
    address: "Financial District, Hyderabad",
    description: "Sky Zone is a trampoline park with freestyle jumping areas, dodgeball courts, foam pits, and a warrior course. High-energy fun for kids and adults alike.",
    bestTimeToVisit: "11:00 AM - 6:00 PM",
    recommendedFor: ["Family", "Friends", "Kids"],
    tags: ["Trampoline", "Dodgeball", "Active", "Indoor"],
    mood: ["fun", "adventure"],
    companion: ["friends", "family", "college"],
    photos: [ENTERTAINMENT_IMAGES[6], ENTERTAINMENT_IMAGES[0], ENTERTAINMENT_IMAGES[4]],
    reviews: [
      { id: "r38", user: "Sanjay L.", rating: 4, text: "Great workout disguised as fun! Kids did not want to leave.", date: "6 days ago" },
    ],
    lat: 17.392,
    lng: 78.4937,
  },
  {
    id: "entertainment_8",
    name: "Snow World Hyderabad",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "entertainment",
    image: ENTERTAINMENT_IMAGES[7],
    rating: 4.3,
    reviewCount: 4200,
    distance: 1.6,
    priceLevel: 3,
    isOpen: true,
    address: "Lower Tank Bund, Hyderabad",
    description: "Snow World is a unique indoor snow theme park where you can experience snowfall, build snowmen, and enjoy snow slides at sub-zero temperatures. A rare experience in tropical India!",
    bestTimeToVisit: "11:00 AM - 4:00 PM",
    recommendedFor: ["Family", "Kids", "Tourists"],
    tags: ["Snow", "Indoor", "Unique", "Winter Experience"],
    mood: ["fun", "adventure"],
    companion: ["family", "friends", "parents"],
    photos: [ENTERTAINMENT_IMAGES[7], ENTERTAINMENT_IMAGES[1], ENTERTAINMENT_IMAGES[5]],
    reviews: [
      { id: "r39", user: "Lavanya B.", rating: 5, text: "Playing in snow in Hyderabad! Kids were absolutely thrilled.", date: "3 days ago" },
    ],
    lat: 17.393,
    lng: 78.4947,
    trending: true,
  },
  {
    id: "entertainment_9",
    name: "The Hidden Castle",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "entertainment",
    image: ENTERTAINMENT_IMAGES[8],
    rating: 4.4,
    reviewCount: 670,
    distance: 7.5,
    priceLevel: 1,
    isOpen: true,
    address: "Gandipet, Hyderabad",
    description: "The Hidden Castle is a medieval-themed adventure resort with zip-lining, paintball, archery, and themed dining. Live out your fantasy in a castle setting.",
    bestTimeToVisit: "10:00 AM - 5:00 PM",
    recommendedFor: ["Friends", "College Trips", "Corporate Events"],
    tags: ["Castle", "Paintball", "Zip-Line", "Themed"],
    mood: ["adventure", "fun"],
    companion: ["friends", "college"],
    photos: [ENTERTAINMENT_IMAGES[8], ENTERTAINMENT_IMAGES[2], ENTERTAINMENT_IMAGES[6]],
    reviews: [
      { id: "r40", user: "Manish P.", rating: 5, text: "Paintball in a castle! What more could you ask for?", date: "1 week ago" },
    ],
    lat: 17.394,
    lng: 78.4957,
  },
  {
    id: "entertainment_10",
    name: "Runway 9",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    type: "entertainment",
    image: ENTERTAINMENT_IMAGES[9],
    rating: 4.0,
    reviewCount: 1340,
    distance: 5.0,
    priceLevel: 2,
    isOpen: true,
    address: "Shamshabad, Hyderabad",
    description: "Runway 9 is a unique aviation-themed dining and entertainment venue built around a decommissioned aircraft. Dine inside a plane, enjoy go-karting, and explore themed zones.",
    bestTimeToVisit: "6:00 PM - 10:00 PM",
    recommendedFor: ["Family", "Couples", "Unique Experience"],
    tags: ["Aviation", "Themed", "Go-Kart", "Unique"],
    mood: ["fun", "adventure", "romantic"],
    companion: ["friends", "family", "girlfriend", "boyfriend"],
    photos: [ENTERTAINMENT_IMAGES[9], ENTERTAINMENT_IMAGES[3], ENTERTAINMENT_IMAGES[7]],
    reviews: [
      { id: "r41", user: "Shreya V.", rating: 4, text: "Dining inside a real airplane is such a unique experience!", date: "5 days ago" },
    ],
    lat: 17.395,
    lng: 78.4967,
  },
];

export const REELS: Reel[] = [
  { id: "re1", placeId: "restaurants_1", placeName: "Paradise Biryani", image: RESTAURANT_IMAGES[6], caption: "The legendary Hyderabadi Dum Biryani at Paradise", creator: "FoodieHyd", likes: 8341, views: 45200 },
  { id: "re2", placeId: "adventure_6", placeName: "Necklace Road", image: ADVENTURE_IMAGES[5], caption: "Golden hour cycling at Necklace Road", creator: "HydExplorer", likes: 5623, views: 32100 },
  { id: "re3", placeId: "cafes_6", placeName: "Cafe Niloufer", image: CAFE_IMAGES[5], caption: "Irani chai and Osmania biscuits - a Hyderabadi ritual", creator: "ChaiAddict", likes: 6876, views: 29800 },
  { id: "re4", placeId: "entertainment_4", placeName: "Smaaash", image: ENTERTAINMENT_IMAGES[3], caption: "VR gaming night with the squad!", creator: "GamerHyd", likes: 3421, views: 21500 },
  { id: "re5", placeId: "restaurants_8", placeName: "Olive Bistro", image: RESTAURANT_IMAGES[7], caption: "Lakeside dinner at sunset - pure magic", creator: "DateNightHyd", likes: 4512, views: 28900 },
  { id: "re6", placeId: "adventure_9", placeName: "KBR National Park", image: ADVENTURE_IMAGES[8], caption: "Morning jog through the green heart of the city", creator: "FitHyderabad", likes: 6234, views: 41200 },
  { id: "re7", placeId: "cafes_4", placeName: "The Gallery Cafe", image: CAFE_IMAGES[3], caption: "Where art meets coffee - The Gallery Cafe", creator: "ArtCafe", likes: 1987, views: 12300 },
  { id: "re8", placeId: "entertainment_8", placeName: "Snow World Hyderabad", image: ENTERTAINMENT_IMAGES[7], caption: "Snowfall in Hyderabad?! Snow World is unreal", creator: "FunZoneHyd", likes: 7145, views: 51800 },
  { id: "re9", placeId: "adventure_1", placeName: "Wonderla Hyderabad", image: ADVENTURE_IMAGES[0], caption: "Recoil roller coaster - not for the faint hearted!", creator: "ThrillSeeker", likes: 4210, views: 33400 },
  { id: "re10", placeId: "restaurants_4", placeName: "Ohri's Jiva Imperia", image: RESTAURANT_IMAGES[3], caption: "Rooftop dining with city lights", creator: "LuxuryDining", likes: 3890, views: 24600 },
];

export const COMPANIONS = [
  { id: "friends", label: "Friends", icon: "people" as const },
  { id: "girlfriend", label: "Partner", icon: "heart" as const },
  { id: "boyfriend", label: "Date", icon: "heart-outline" as const },
  { id: "college", label: "College Crew", icon: "school" as const },
  { id: "parents", label: "Parents", icon: "home" as const },
  { id: "family", label: "Family", icon: "people-circle" as const },
  { id: "solo", label: "Solo", icon: "person" as const },
];

export const MOODS = [
  { id: "chill", label: "Chill & Relaxed", icon: "leaf" as const, color: "#2EC4B6" },
  { id: "romantic", label: "Romantic", icon: "heart" as const, color: "#FF6B6B" },
  { id: "fun", label: "Fun & Loud", icon: "musical-notes" as const, color: "#FFD93D" },
  { id: "adventure", label: "Adventure", icon: "compass" as const, color: "#E94560" },
  { id: "peaceful", label: "Peaceful", icon: "flower" as const, color: "#A78BFA" },
  { id: "budget", label: "Budget Hangout", icon: "wallet" as const, color: "#34D399" },
];

export const PLACE_TYPES = [
  { id: "restaurant", label: "Restaurant", icon: "restaurant" as const },
  { id: "cafe", label: "Cafe", icon: "cafe" as const },
  { id: "adventure", label: "Adventure", icon: "trail-sign" as const },
  { id: "entertainment", label: "Entertainment", icon: "game-controller" as const },
];

export function getPriceLabel(level: number): string {
  return "$".repeat(level);
}

export function filterPlaces(
  places: Place[],
  filters: {
    companion?: string;
    mood?: string;
    type?: string;
    priceLevel?: number;
    maxDistance?: number;
    minRating?: number;
    openNow?: boolean;
    search?: string;
  }
): Place[] {
  return places.filter((place) => {
    if (filters.companion && !place.companion.includes(filters.companion)) return false;
    if (filters.mood && !place.mood.includes(filters.mood)) return false;
    if (filters.type && place.type !== filters.type) return false;
    if (filters.priceLevel && place.priceLevel > filters.priceLevel) return false;
    if (filters.maxDistance && place.distance > filters.maxDistance) return false;
    if (filters.minRating && place.rating < filters.minRating) return false;
    if (filters.openNow && !place.isOpen) return false;
    if (filters.search) {
      const q = filters.search.toLowerCase();
      return (
        place.name.toLowerCase().includes(q) ||
        place.tags.some((t) => t.toLowerCase().includes(q)) ||
        (place.cuisine && place.cuisine.toLowerCase().includes(q)) ||
        place.type.toLowerCase().includes(q) ||
        place.city.toLowerCase().includes(q)
      );
    }
    return true;
  });
}
